### PR TITLE
Add audit to readme and remove create3 deployment

### PR DESCRIPTION
**Pull request by zodahu**

### CODE REVIEW

**Review by Jeff-CCH — APPROVED** [review]
LGTM

**Comment by hihiben** [comment]
Do we need to keep `script/DeployCREATE3Factory.s.sol` and the related `create3-factory` file? Such as submodules and remappings.

**Comment by zodahu** [comment]
Yes, 

> Do we need to keep `script/DeployCREATE3Factory.s.sol` and the related `create3-factory` files? Such as submodules and remappings.

Yes, `DeployLocal.s.sol` needs these to test.

**Review by hihiben — APPROVED** [review]
LGTM

**Pull request merged**
